name: CPP module test for global tags
trigger: none
pr:
  - main

resources:
  repositories:
    - repository: cppAzureDevOpsTemplates
      type: github
      name: hmcts/cpp-azure-devops-templates
      endpoint: "hmcts"
      ref: 'EI-1799'

extends:
  template: pipelines/terratest.yaml@cppAzureDevOpsTemplates
  parameters:
    agentPool: "MDV-ADO-AGENTS-01"
    azureServiceConnection: "ado_nonlive_workload_identity"
    terratestTimeout: "30"
    tfversion: 1.5.3
